Add desktop version
ivangonzalez224/portfolio.io pull request #7
Opened 2023-06-10 17:07 UTC by ivangonzalez224

It is my personal portfolio project and I have added the following new features:

Added the cards needed for the works section html skeleton.
Added styles for the desktop version using media queries.
Added the folder with the images used in the desktop version.

2023-06-10 19:17 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Fentahunn, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 19:17 UTC, Qoosim commented on index.html
>                      </ul>
- [ ] It is required to stick to the Figma design as close as possible. Kindly look into below two screenshots and walk your design alongside the figma design.

### Your Design
![your-header](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/197c9cda-5ebb-4543-af78-d8bb261734ff)

### Figma Design
![figma-header](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/029bceb2-1942-45ab-b87d-75ddd0ccf5d8)

2023-06-10 19:17 UTC, Qoosim commented on index.html
>                  </div>
- [ ] It is required to stick to the Figma design as close as possible. Kindly look into below two screenshots and walk your design alongside the figma design.

### Your Design
![your-headline-2](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/93960b54-cd8d-4411-9438-ce566a00b0c3)

### Figma Design
![figma-headling](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/6133752c-f8cf-444f-a69b-7db6fc75103c)

2023-06-10 19:17 UTC, Qoosim commented on index.html
> +                    <img src="images/illustrationDesktop.png" alt="Robot Illustration">
- [ ] In your mobile version before the desktop version. You were asked to add the background image with css background-image property not with the `img`. Kindly use the same approach for your desktop version.

2023-06-10 19:17 UTC, Qoosim commented on index.html
> +                    <img src="images/illustrationAboutDesk.png" alt="Robot illustration">
- [ ] In your mobile version before the desktop version. You were asked to add the background image with css background-image property not with the `img`. Kindly use the same approach for your desktop version.

### Your Design
![your-about](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/a8141e41-9cb5-42bf-86bf-e0ffa2075f99)

### Figma Design
![figma-about](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/a7c7ba5a-b3e4-46c1-b398-3d530f37f318)

- [ ] Also, it is required that your design for the desktop version must not affect your already designed mobile version. I would recommend you to check the background image for the about myself section as that has created horizontal scroll bar. Kindly attend to it and fix.

### Your App (Mobile version)
[app-behave.webm](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/16983b42-e91e-4d1b-83c4-fd51f04fcd83)

2023-06-10 19:17 UTC, Qoosim commented on index.html
>              <input type="text" aria-label="name" name="user_name" maxlength="30" placeholder="Full name" required/>
- [ ] It is required to stick to the Figma design as close as possible. Kindly look into below two screenshots and walk your design alongside the figma design.

### Your Design
![your-contact-form](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/62204b3e-5f62-4ebc-bbdd-4c1df43be304)

### Figma Design
![figma-contact-form](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/9ddde091-b256-4225-8ebd-8db344cca28f)

2023-06-10 19:17 UTC, Qoosim commented on index.html
> +                <div class="worksCard worksCard_1">
- [ ] My Recent works and the horizontal line are on the same line on the Figma design while yours are on different line. Kindly fix that.
- [ ] I would like to suggest that, you reduce the margin between the line and the first project so as to match the figma design.

### Your Design
![your-work-title](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/f04725f5-c748-4032-8526-9d271f4c5450)

### Figma Design
![figma-work-title](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/33b1cace-3e31-402a-b2bf-7e5aaddffacb)

2023-06-10 19:17 UTC, Qoosim commented on index.html
> +                </div>
- [ ] There's an horizontal scroll bar at the bottom of your page. Kindly look into that and fix.
- [ ] Also, it is required to produce a close replica of the Figma design. This includes margin, padding among others. Kindly look into the two screenshots below and walk your design alongside the figma design.

### Your Design
![your-project-list](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/29a157df-25d6-4278-bf17-13a9f568f4d3)

### Figma Design
![figma-project-list](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/26597432/f892ee31-1e78-4fb2-b488-c98dd8648615)

2023-06-11 01:56 UTC, Shedrack-Sunday requested changes
Hello @ivangonzalez224       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Kudos on the design and heeding to suggested changes✔️ 
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirements 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-11 01:56 UTC, Shedrack-Sunday commented on index.html
> +                        <img src="images/medium.png" alt="Medium Icon">
- [ ] Good job making a little bit of adjustment based on the Figma design 👍 
- As you can see below, you'll agree with me that there are little adjustments let on the extra margin you have from the `nav` top to the background image of the header and where the text is placed. Kindly adjust your design while taking reference from the template provided to have a close replica 👍 

## Your work:
![image](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/50990925/d39440c2-9bb2-4619-9798-44de7524c5f1)

## Figma:
![image](https://github.com/ivangonzalez224/Portfolio-mobile-first/assets/50990925/658b05a9-72fa-4e1e-b9b2-9a399668ad38)

2023-06-11 03:43 UTC, usorfaitheloho approved these changes
Hi @ivangonzalez224  , 
# STATUS: APPROVED! 🥇 💯 
- [x] Very Nice Design, Keep it up!!
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-11 04:00 UTC, merged

2023-06-13 14:21 UTC, Godedict commented on README.md
>  <p align="right">(<a href="#readme-top">back to top</a>)</p>
dezgfhcvjbhztfi

2023-06-13 14:29 UTC, Godedict reviewed
Kindly make changes 👌

2023-06-13 14:29 UTC, Godedict commented on style.css
> +  @media (min-width: 768px) {
Kindly add a hover function for this card. Hover allows the card to change theme color and sticks better with the figma design.

2023-06-13 15:33 UTC, Fentahunn commented
This dosenot concern me , please donot send me again
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/13/23,
06:33:12 PM

On Tue, Jun 13, 2023 at 5:29 PM Adeniyi Aderounmu ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Kindly make changes 👌
> ------------------------------
>
> In style.css
> <https://github.com/ivangonzalez224/portfolio.io/pull/7#discussion_r1228224298>
> :
>
> >  }
>
>  .navBtnMessage.active .messageBtn {
>    pointer-events: none;
> +
> +  @media (min-width: 768px) {
>
> Kindly add a hover function for this card. Hover allows the card to change
> theme color and sticks better with the figma design.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ivangonzalez224/portfolio.io/pull/7#pullrequestreview-1477324119>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZENTQQNPZHFNQKV4AZBWKDXLB2MTANCNFSM6AAAAAAZBZFDGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>